### PR TITLE
Partial withdraw

### PR DESCRIPTION
**Pull request by brittcyr**

### CODE REVIEW

**Comment by brittcyr** [comment]
Fixes #39

**Review by DonDuala — APPROVED** [review]
If you deploy to devnet, Dev-Sub-8 is past subscription date but not expired so I can test

**Comment by brittcyr** [comment]
> If you deploy to devnet, Dev-Sub-8 is past subscription date but not expired so I can test

deploying now. but I am pretty confident that the anchor testing covers this

**Comment by brittcyr** [comment]
> > If you deploy to devnet, Dev-Sub-8 is past subscription date but not expired so I can test
> 
> deploying now. but I am pretty confident that the anchor testing covers this

Deployment to devnet done

**Comment by DonDuala** [comment]
Devnet test looks good https://solana.fm/tx/26ZcA7xPWnTo9rgwN1Si4w6LBRQQz5zZhudEyMgr51VdKtArrXo2QRuzZbGuLJHtKqiAjAj6HjVX74o1S9zhe3nh?cluster=devnet

**Pull request merged**
